name: Build
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Gcc and GDB
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install gdb python3-pytest python3-pandas
          python3 -m pip install --upgrade pip
      - name: configure
        run: |
          mkdir build
          cd build
          cmake ../ -G Ninja
      - name: ninja build
        run: |
          cd build
          ninja
      - name: ctest
        run: |
          cd build
          ctest -VV
          

