name: pre-commit
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: create venv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pre-commit

      - name: run pre-commit
        run: |
          source venv/bin/activate
          pre-commit run --all-files
